# Generated by Django 5.1.3 on 2024-11-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PROCESO', 'PROCESO'), ('COMPLETADA', 'COMPLETADA')], default='PENDIENTE', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'public"."todo',
                'ordering': ['-fecha_actualizacion'],
                'get_latest_by': '-fecha_actualizacion',
            },
        ),
    ]
